[package]
name = "pxls-placemaper"
version = "0.3.2"
edition = "2021"
authors = ["Chssam"]

[dependencies]
xz2 = "0.1"
image = "0.24"
sha256 = "1.4"
hex = "0.4"
ron = "0.8"
anyhow = "1.0"

[dependencies.serde]
version = "1.0"
features = ["derive"]